<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QueueMS.Appilication\QueueMS.Appilication.csproj" />
    <ProjectReference Include="..\QueueMS.Domain\QueueMS.Domain.csproj" />
    <ProjectReference Include="..\QueueMS.Infrastructure\QueueMS.Infrastructure.csproj" />
  </ItemGroup>

</Project>
